-- 使用者列表 TB_USER
CREATE TABLE TB_USER (
    USER_NO VARCHAR2(20) NOT NULL,
    NANNY_ID VARCHAR2(20),
    USER_PASSWORD VARCHAR2(256) NOT NULL,
    USER_NAME NVARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(320) NOT NULL,
	MOBILE VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);
COMMENT ON TABLE TB_USER IS '使用者列表';
COMMENT ON COLUMN TB_USER.USER_NO IS '使用者編號, Snowflake ID';
COMMENT ON COLUMN TB_USER.NANNY_ID IS '保姆編號, Ref ESB22012.TB_NANNY.NANNY_ID';
COMMENT ON COLUMN TB_USER.USER_PASSWORD IS '使用者密碼';
COMMENT ON COLUMN TB_USER.USER_NAME IS '使用者姓名';
COMMENT ON COLUMN TB_USER.EMAIL IS '使用者信箱';
COMMENT ON COLUMN TB_USER.MOBILE IS '使用者電話號碼';
-------------------------------------------------------------------------------------




-- 寵物保姆列表 TB_NANNY
CREATE TABLE TB_NANNY (
    NANNY_ID VARCHAR2(20) NOT NULL,
    SELF_INTRODUCTION NVARCHAR2(500) NOT NULL,
    SERVICE_LOCATION CHAR(1) NOT NULL,
	NANNY_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CERTIFICATION_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_NANNY PRIMARY KEY(NANNY_ID)
);
COMMENT ON TABLE TB_NANNY IS '寵物保姆列表';
COMMENT ON COLUMN TB_NANNY.NANNY_ID IS '保姆編號, Snowflake ID';
COMMENT ON COLUMN TB_NANNY.SELF_INTRODUCTION IS '自我介紹';
COMMENT ON COLUMN TB_NANNY.SERVICE_LOCATION IS '服務區域';
COMMENT ON COLUMN TB_NANNY.NANNY_STATUS IS '保姆身分狀態';
COMMENT ON COLUMN TB_NANNY.CERTIFICATION_STATUS IS '證照狀態';
-------------------------------------------------------------------------------------




-- 保姆服務列表 TB_NANNY_SERVICE
CREATE TABLE TB_NANNY_SERVICE (
    SERVICE_SEQ_NO VARCHAR2(20) NOT NULL,
    NANNY_ID VARCHAR2(20) NOT NULL,
    SERVICE_TYPE VARCHAR2(2) NOT NULL,
    SERVICE_NAME NVARCHAR2(50) NOT NULL,
	PRICE NUMBER(6,2) NOT NULL,
    ACCEPTABLE_SPECIES VARCHAR2(50) NOT NULL,
    ACCEPTABLE_AMOUNTS NUMBER(1,0) NOT NULL,
    ACCEPTABLE_SIZE VARCHAR2(2) NOT NULL,
    SUPERVISION VARCHAR2(2) NOT NULL,
	EXCRETION_FREQUENCY VARCHAR2(2) NOT NULL,
	WALK_FREQUENCY VARCHAR2(2) NOT NULL,
    EMERGENCY_DELIVERY CHAR(1) DEFAULT 'N' NOT NULL,
    LAST_MIN_BOOKING CHAR(1) DEFAULT 'N' NOT NULL,
    CASE_AMOUNTS NUMBER(8,0) DEFAULT 0 NOT NULL,
    SERVICE_SCORE NUMBER(2,1),
	SERVICE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_NANNY_SERVICE PRIMARY KEY(SERVICE_SEQ_NO)
);
COMMENT ON TABLE TB_NANNY_SERVICE IS '保姆服務列表';
COMMENT ON COLUMN TB_NANNY_SERVICE.SERVICE_SEQ_NO IS '服務流水號, Snowflake ID';
COMMENT ON COLUMN TB_NANNY_SERVICE.NANNY_ID IS '保姆編號, Ref ESB22012.TB_NANNY.NANNY_ID';
COMMENT ON COLUMN TB_NANNY_SERVICE.SERVICE_TYPE IS '服務類型';
COMMENT ON COLUMN TB_NANNY_SERVICE.SERVICE_NAME IS '服務名稱';
COMMENT ON COLUMN TB_NANNY_SERVICE.PRICE IS '服務價格';
COMMENT ON COLUMN TB_NANNY_SERVICE.ACCEPTABLE_SPECIES IS '可接受寵物種類';
COMMENT ON COLUMN TB_NANNY_SERVICE.ACCEPTABLE_AMOUNTS IS '可接受寵物數量';
COMMENT ON COLUMN TB_NANNY_SERVICE.ACCEPTABLE_SIZE IS '可接受最大寵物體型';
COMMENT ON COLUMN TB_NANNY_SERVICE.SUPERVISION IS '可提供的監督級別';
COMMENT ON COLUMN TB_NANNY_SERVICE.EXCRETION_FREQUENCY IS '可提供排泄次數';
COMMENT ON COLUMN TB_NANNY_SERVICE.WALK_FREQUENCY IS '可提供步行次數';
COMMENT ON COLUMN TB_NANNY_SERVICE.EMERGENCY_DELIVERY IS '緊急狀況載送';
COMMENT ON COLUMN TB_NANNY_SERVICE.LAST_MIN_BOOKING IS '最後一刻預訂';
COMMENT ON COLUMN TB_NANNY_SERVICE.CASE_AMOUNTS IS '已提供服務次數';
COMMENT ON COLUMN TB_NANNY_SERVICE.SERVICE_SCORE IS '服務總評';
COMMENT ON COLUMN TB_NANNY_SERVICE.SERVICE_STATUS IS '服務狀態';
-------------------------------------------------------------------------------------




-- 寄養者請求列表 TB_SERVICE_CASE
CREATE TABLE TB_SERVICE_CASE (
    CASE_NO VARCHAR2(20) NOT NULL,
    APPOINTER VARCHAR2(20) NOT NULL,
--    SERVICE_SEQ_NO VARCHAR2(20),
	SERVICE_TYPE VARCHAR2(2) NOT NULL,
    ACCEPTABLE_PRICE NUMBER(6,2) NOT NULL,
    PET_SPECIES VARCHAR2(50) NOT NULL,
    PET_AMOUNTS NUMBER(1,0) NOT NULL,
    PET_SIZE VARCHAR2(2) NOT NULL,
	NEED_TO_KNOW NVARCHAR2(500),
	SERVICE_START_DATE DATE NOT NULL,
    SERVICE_DUE_DATE DATE NOT NULL,
    LOCATION CHAR(1) NOT NULL,
    REQUIRED_VISIT_FREQUENCY VARCHAR2(2) NOT NULL,
    CASE_COMMENT NVARCHAR2(500),
	CASE_SCORE NUMBER(1,0),
    CASE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_SERVICE_CASE PRIMARY KEY(CASE_NO)
);
COMMENT ON TABLE TB_SERVICE_CASE IS '寄養者請求列表';
COMMENT ON COLUMN TB_SERVICE_CASE.CASE_NO IS '寄養者請求編號, Snowflake ID';
COMMENT ON COLUMN TB_SERVICE_CASE.APPOINTER IS '發送請求者, Ref ESB22012.TB_USER.USER_NO';
--COMMENT ON COLUMN TB_SERVICE_CASE.SERVICE_SEQ_NO IS '服務流水號, Ref ESB22012.TB_NANNY_SERVICE.SERVICE_SEQ_NO';
COMMENT ON COLUMN TB_SERVICE_CASE.SERVICE_TYPE IS '服務類型';
COMMENT ON COLUMN TB_SERVICE_CASE.ACCEPTABLE_PRICE IS '可接受最高價格';
COMMENT ON COLUMN TB_SERVICE_CASE.PET_SPECIES IS '寵物種類';
COMMENT ON COLUMN TB_SERVICE_CASE.PET_AMOUNTS IS '寵物數量';
COMMENT ON COLUMN TB_SERVICE_CASE.PET_SIZE IS '寵物最大體型';
COMMENT ON COLUMN TB_SERVICE_CASE.NEED_TO_KNOW IS '保姆須知';
COMMENT ON COLUMN TB_SERVICE_CASE.SERVICE_START_DATE IS '需求起始日';
COMMENT ON COLUMN TB_SERVICE_CASE.SERVICE_DUE_DATE IS '需求結束日';
COMMENT ON COLUMN TB_SERVICE_CASE.LOCATION IS '所在區域';
COMMENT ON COLUMN TB_SERVICE_CASE.REQUIRED_VISIT_FREQUENCY IS '最低拜訪次數要求';
COMMENT ON COLUMN TB_SERVICE_CASE.CASE_COMMENT IS '服務評價說明';
COMMENT ON COLUMN TB_SERVICE_CASE.CASE_SCORE IS '服務評分';
COMMENT ON COLUMN TB_SERVICE_CASE.CASE_STATUS IS '請求單狀態';
-------------------------------------------------------------------------------------




-- 寵物保姆證書列表 TB_NANNY_CERTIFICATION
CREATE TABLE TB_NANNY_CERTIFICATION (
    NANNY_ID VARCHAR2(20) NOT NULL,
    CERTIFICATION BLOB,
    CONSTRAINT PK_NANNY_CERTIFICATION PRIMARY KEY(NANNY_ID)
);
COMMENT ON TABLE TB_NANNY_CERTIFICATION IS '寵物保姆證書列表';
COMMENT ON COLUMN TB_NANNY_CERTIFICATION.NANNY_ID IS '保姆編號, Ref ESB22012.TB_NANNY.NANNY_ID';
COMMENT ON COLUMN TB_NANNY_CERTIFICATION.CERTIFICATION IS '保姆證照';
-------------------------------------------------------------------------------------




-- 保母應聘列表 TB_CASE_APPLICANT
CREATE TABLE TB_CASE_APPLICANT(
    APPLICANT_SEQ_NO VARCHAR2(20) NOT NULL,
    CASE_NO VARCHAR2(20) NOT NULL,
    NANNY_ID VARCHAR2(20) NOT NULL,
	APPLICANT_STATUS CHAR(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CASE_APPLICANT PRIMARY KEY(APPLICANT_SEQ_NO)
);
COMMENT ON TABLE TB_CASE_APPLICANT IS '保母應聘列表';
COMMENT ON COLUMN TB_CASE_APPLICANT.APPLICANT_SEQ_NO IS '應聘流水號, Snowflake ID';
COMMENT ON COLUMN TB_CASE_APPLICANT.CASE_NO IS '寄養者請求編號, Ref ESB22012.TB_SERVICE_CASE.CASE_NO';
COMMENT ON COLUMN TB_CASE_APPLICANT.NANNY_ID IS '保姆編號, Ref ESB22012.TB_NANNY.NANNY_ID';
COMMENT ON COLUMN TB_CASE_APPLICANT.APPLICANT_STATUS IS '應聘狀態';
-------------------------------------------------------------------------------------
--ALTER TABLE TB_NANNY MODIFY ( NANNY_STATUS CHAR(1) DEFAULT 'Y' );
--ALTER TABLE TB_SERVICE_CASE MODIFY ( CASE_STATUS CHAR(1) DEFAULT 'Y' );
--ALTER TABLE TB_NANNY MODIFY ( CERTIFICATION_STATUS CHAR(1) DEFAULT 'N' NOT NULL);
--ALTER TABLE TB_SERVICE_CASE MODIFY SERVICE_SEQ_NO NULL;

COMMIT;


















-- /***** 暫不使用 *****/ ---------------------------------------------------------------------------------------
DROP TABLE esb22012.TB_EMPLOYEE;
DROP TABLE esb22012.TB_NOTIFICATION;
-- 平台員工列表 TB_EMPLOYEE
CREATE TABLE TB_EMPLOYEE (
    EMPLOYEE_NO VARCHAR2(20) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR2(256) NOT NULL,
    EMAIL VARCHAR2(320) NOT NULL,
    OCCUPATION VARCHAR2(2) NOT NULL,
	SUSPEND CHAR(1) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMPLOYEE_NO)
);
COMMENT ON TABLE TB_EMPLOYEE IS '平台員工列表';
COMMENT ON COLUMN TB_EMPLOYEE.EMPLOYEE_NO IS '員工編號';
COMMENT ON COLUMN TB_EMPLOYEE.EMPLOYEE_PASSWORD IS '員工密碼';
COMMENT ON COLUMN TB_EMPLOYEE.EMAIL IS '員工個人信箱';
COMMENT ON COLUMN TB_EMPLOYEE.OCCUPATION IS '員工職稱';
COMMENT ON COLUMN TB_EMPLOYEE.SUSPEND IS '員工狀態';
-------------------------------------------------------------------------------------
-- 通知紀錄列表 TB_NOTIFICATION
CREATE TABLE TB_NOTIFICATION (
    NOTIFICATION_NO VARCHAR2(20) NOT NULL,
    CASE_NO VARCHAR2(20) NOT NULL,
    NOTIFEE VARCHAR2(20) NOT NULL,
    NOTIFICATION_CONTENT NVARCHAR2(300) NOT NULL,
	NOTIFICATION_DATE DATE NOT NULL,
    NOTIFICATION_STATUS CHAR(1) DEFAULT 0 NOT NULL,
    READ_STATUS CHAR(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY(NOTIFICATION_NO)
);
COMMENT ON TABLE TB_NOTIFICATION IS '通知紀錄列表';
COMMENT ON COLUMN TB_NOTIFICATION.NOTIFICATION_NO IS '通知編號';
COMMENT ON COLUMN TB_NOTIFICATION.CASE_NO IS '寄養者請求編號, Ref ESB22012.TB_SERVICE_CASE.CASE_NO';
COMMENT ON COLUMN TB_NOTIFICATION.NOTIFEE IS '被通知人, Ref ESB22012.TB_USER.USER_NO';
COMMENT ON COLUMN TB_NOTIFICATION.NOTIFICATION_CONTENT IS '通知訊息內容';
COMMENT ON COLUMN TB_NOTIFICATION.NOTIFICATION_DATE IS '通知日期';
COMMENT ON COLUMN TB_NOTIFICATION.NOTIFICATION_STATUS IS '通知訊息狀態';
COMMENT ON COLUMN TB_NOTIFICATION.READ_STATUS IS '讀取狀態';
-------------------------------------------------------------------------------------
